// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

package structs

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Message struct {
	Creator          *string `protobuf:"bytes,1,opt,name=creator" json:"creator,omitempty"`
	Receiver         *string `protobuf:"bytes,2,opt,name=receiver" json:"receiver,omitempty"`
	CreatedAt        *int64  `protobuf:"varint,3,opt,name=created_at" json:"created_at,omitempty"`
	Id               *string `protobuf:"bytes,4,opt,name=id" json:"id,omitempty"`
	Payload          *string `protobuf:"bytes,5,opt,name=payload" json:"payload,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *Message) Reset()         { *this = Message{} }
func (this *Message) String() string { return proto.CompactTextString(this) }
func (*Message) ProtoMessage()       {}

func (this *Message) GetCreator() string {
	if this != nil && this.Creator != nil {
		return *this.Creator
	}
	return ""
}

func (this *Message) GetReceiver() string {
	if this != nil && this.Receiver != nil {
		return *this.Receiver
	}
	return ""
}

func (this *Message) GetCreatedAt() int64 {
	if this != nil && this.CreatedAt != nil {
		return *this.CreatedAt
	}
	return 0
}

func (this *Message) GetId() string {
	if this != nil && this.Id != nil {
		return *this.Id
	}
	return ""
}

func (this *Message) GetPayload() string {
	if this != nil && this.Payload != nil {
		return *this.Payload
	}
	return ""
}

func init() {
}
